### PR TITLE
In addition to handling drag gesture changes & ending, also handle ca…

### LINKED ISSUE #148: When swiping up from safe area to show app switcher, bottom sheet can be dragged to position not included in switchablePositions
**Describe the bug**
When swiping up from safe area to show app switcher, bottom sheet can be dragged to position not included in switchablePositions.

**Minimal reproduce-able code**
```
import SwiftUI
import BottomSheet

struct ContentView: View {
    @State var bottomSheetPosition: BottomSheetPosition = .hidden
    
    var body: some View {
        GeometryReader { proxy in
            ZStack {
                VStack {
                    Button(action: {
                        bottomSheetPosition = .absolute(250)
                    }) {
                        Text("Show sheet")
                    }
                }
                Text("250 px")
                    .position(x: 20, y: proxy.size.height - 250)
            }
            .padding()
            .bottomSheet(bottomSheetPosition: $bottomSheetPosition, switchablePositions: [
                .absolute(250)
            ], headerContent: {
                Text("Testing").font(.title).bold().padding()
            }) {
                Text("Testing")
            }
            .showCloseButton()
        }
    }
}

#Preview {
    ContentView()
}
```

**Expected behavior**
Bottom sheet should not resize when dragging on safe area to show app switcher. At least it should not switch to position not included in switchablePositions.

**Video**

In this slow motion video, I drag on the bottom safe area to show app switcher. While the app switcher is displayed, the bottom sheet is simultaneously being resized and switched to position not included in the switchablePositions. The maximum size in the switchablepositions is 250px but the sheet ends up taller than that (it covers the text positioned at 250px).

https://github.com/lucaszischka/BottomSheet/assets/2369584/002acdb3-26e2-43a5-96dc-7f317e653976

**Target version**
- Environment: iOS
- Version: 3.1.1

### PR DESCRIPTION
**Pull request by juhieta**
…ncelled drag gesture. Fixes #148.

### CODE REVIEW

**Comment by lucaszischka** [comment]
Hello Jukka Hietanen,
first of all, thank you for taking the time to fix this issue yourself. ❤️
Im currently very busy, so I don't have time to test this PR; however the code LGTM and after you fix the MacOS build I will merge it into `main`. Also consider adding
> **v3.1.2**
> - Fixed drag animation bug #148 (#149, thx @juhieta)

to `CHANGELOG.md`.

Anyway, I will not release a new version until I had time to test it. This means for you (or anyone else having this issue), that you will either have to use the `main` branch or your current fork.

Sorry for the inconvenience and thank you very much for helping me out!

Greetings from Munich,
Lucas

**Comment by zchwyng** [comment]
Thanks! ❤️❤️ Can we get this merged? This bug makes dragging from the bottom pretty much a no go, imho. I've tested it on a real device with iOS 17.3.1 on an iPhone 12 mini and a bunch of different iPhone and iPad simulators with iOS 17.0. I will try this in production on a small user base.

**Comment by fickledogfish** [comment]
@juhieta could you apply this patch to the PR? It should fix the macOS build. 😺 

```patch
diff --git a/Sources/BottomSheet/Helper/Extensions/ViewExtension.swift b/Sources/BottomSheet/Helper/Extensions/ViewExtension.swift
index 4a49adf..689f760 100644
--- a/Sources/BottomSheet/Helper/Extensions/ViewExtension.swift
+++ b/Sources/BottomSheet/Helper/Extensions/ViewExtension.swift
@@ -13,7 +13,7 @@ import Combine
 internal extension View {
     /// A backwards compatible wrapper for iOS 14 onChange
     @ViewBuilder func valueChanged<T: Equatable>(value: T, onChange: @escaping (T) -> Void) -> some View {
-        if #available(iOS 14.0, *) {
+        if #available(iOS 14.0, macOS 11.0, *) {
             self.onChange(of: value, perform: onChange)
         } else {
             self.onReceive(Just(value)) { (value) in
```

**Comment by timath98** [comment]
Hi, do you think there will be a delivery soon for this fix? 
Thanks :)

**Pull request merged**
